Pandas : Panel Dataframe

Helps to import, display , manipulate and export tabular data.

In [1]:
import pandas as pd

print(pd.__version__)

3.0.3

Series: A 1-Dimensional labeled array that can hold any datatype. It can be taken like a single column in a spreadsheet.

In [ ]:
data = [1011 , 1022, 100]


series = pd.Series(data)          # Series() is a constructor and not a function

print(series)

0    1100.1
1     102.2
2      True
dtype: object

In [14]:
data = [1011 , 1022, 100]


series = pd.Series(data, index = {"a" , "b" , "c"})          # we can pass list , tuple, dictionary , set , a numpy array or even another series as index
print(series)

series.loc["a"] =200

print(series.loc["a"])  

print(series.iloc[0])

b    1011
a    1022
c     100
dtype: int64
200
1011

In [15]:
data = [1011 , 1022, 100, 200 , 750 , 800, 670, 69]

series = pd.Series(data, index = ['a' , 'b' , 'c' , 'd' , 'e', 'f' , 'g' , 'h'])

print(series[series >= 200])

a    1011
b    1022
d     200
e     750
f     800
g     670
dtype: int64

In [25]:
calories = {"Day 1" : 1070,
            "Day 2" : 980,
            "Day 3" : 2350,
            "Day 4" : 500}

 
series = pd.Series(calories)  # No need to pass index for dictionary because key acts as an index.

print(series)
print("-----------------------------------------------------")
print(series.loc["Day 2"])
print("-----------------------------------------------------")
print(series.iloc[3])
print("-----------------------------------------------------")
series.loc["Day 4"] += 567

print(series.loc["Day 4"])
print("-----------------------------------------------------")
print(series)

Day 1    1070
Day 2     980
Day 3    2350
Day 4     500
dtype: int64
-----------------------------------------------------
980
-----------------------------------------------------
500
-----------------------------------------------------
1067
-----------------------------------------------------
Day 1    1070
Day 2     980
Day 3    2350
Day 4    1067
dtype: int64

In [26]:
calories = {"Day 1" : 1070,
            "Day 2" : 980,
            "Day 3" : 2350,
            "Day 4" : 500}

 
series = pd.Series(calories)

print(series[series>2000])

Day 3    2350
dtype: int64

In [46]:
# Exercise :

pokemon = {"1":"Bulbasaur",
           "25":"Pikachu",
           "6":"Charizard",
           "706":"Goodra",
           "52":"Meowth",
           "151":"Mew",
           "100":"Voltorb"}

series = pd.Series(pokemon)

print(series)

series.head()

1      Bulbasaur
25       Pikachu
6      Charizard
706       Goodra
52        Meowth
151          Mew
100      Voltorb
dtype: str

1      Bulbasaur
25       Pikachu
6      Charizard
706       Goodra
52        Meowth
dtype: str

Dataframe : A dataframe is a tabular data structure with rows and columns. It is 2 dimensional like a excel spreadsheet

In [47]:
data = {"Name" : ["Pikachu" , "Meowth" , "Charizard" , "Dragonite" , "Mew" , "Goodra"],
        "Post" : ["a", "b" , "c", "d", "e", "f"],
        "age": [11,2,3,4]}


print(data)

print(data["Name"])

{'Name': ['Pikachu', 'Meowth', 'Charizard', 'Dragonite', 'Mew', 'Goodra'], 'Post': ['a', 'b', 'c', 'd', 'e', 'f'], 'age': [11, 2, 3, 4]}
['Pikachu', 'Meowth', 'Charizard', 'Dragonite', 'Mew', 'Goodra']

In [48]:
data = {"Name" : ["Pikachu" , "Meowth" , "Charizard" , "Dragonite" , "Mew" , "Goodra"],
        "Pokedex No.": [25,52,6,149,151,706]}

df = pd.DataFrame(data)

print(df)
print('----------------------------------------')
print(df.head())
print('----------------------------------------')
print(df.tail())
print('----------------------------------------')

        Name  Pokedex No.
0    Pikachu           25
1     Meowth           52
2  Charizard            6
3  Dragonite          149
4        Mew          151
5     Goodra          706
----------------------------------------
        Name  Pokedex No.
0    Pikachu           25
1     Meowth           52
2  Charizard            6
3  Dragonite          149
4        Mew          151
----------------------------------------
        Name  Pokedex No.
1     Meowth           52
2  Charizard            6
3  Dragonite          149
4        Mew          151
5     Goodra          706
----------------------------------------

In [49]:
data = {"Name" : ["Pikachu" , "Meowth" , "Charizard" , "Dragonite" , "Mew" , "Goodra"],
        "Pokedex No.": [25,52,6,149,151,706]}

df = pd.DataFrame(data , index = ['Pokemon 1','Pokemon 2','Pokemon 3','Pokemon 4','Pokemon 5','Pokemon 6'])

print(df)
print('----------------------------------------')
print(df.loc["Pokemon 4"])
print('----------------------------------------')
print(df.iloc[2])
print('----------------------------------------')
print(df.iloc[1,1])      # Access value at index number 1 and column number 1
print('----------------------------------------')
print(df.iat[2,0])            # Same as iloc just faster
print('----------------------------------------')



value1 = df.loc[df["Name"] == 'Pikachu', 'Pokedex No.']
print(value1)
print('----------------------------------------')
value2 = df.loc[df["Name"] == 'Pikachu', 'Pokedex No.'].item()

value3 = df.loc[df["Name"] == 'Pikachu', 'Pokedex No.'].values[0]

print(value2, value3)

                Name  Pokedex No.
Pokemon 1    Pikachu           25
Pokemon 2     Meowth           52
Pokemon 3  Charizard            6
Pokemon 4  Dragonite          149
Pokemon 5        Mew          151
Pokemon 6     Goodra          706
----------------------------------------
Name           Dragonite
Pokedex No.          149
Name: Pokemon 4, dtype: object
----------------------------------------
Name           Charizard
Pokedex No.            6
Name: Pokemon 3, dtype: object
----------------------------------------
52
----------------------------------------
Charizard
----------------------------------------
Pokemon 1    25
Name: Pokedex No., dtype: int64
----------------------------------------
25 25

In [50]:
data = {"Name" : ["Pikachu" , "Meowth" , "Charizard" , "Dragonite" , "Mew" , "Goodra"],
        "Pokedex No.": [25,52,6,149,151,706]}

df = pd.DataFrame(data , index = ['Pokemon 1','Pokemon 2','Pokemon 3','Pokemon 4','Pokemon 5','Pokemon 6'])

print(df)
print('----------------------------------------')

value = df.loc[df["Pokedex No."] == 52 ]
print(value)

print('----------------------------------------')

value = df.loc[df["Pokedex No."] == 52 , 'Name'].item()
print(value)

                Name  Pokedex No.
Pokemon 1    Pikachu           25
Pokemon 2     Meowth           52
Pokemon 3  Charizard            6
Pokemon 4  Dragonite          149
Pokemon 5        Mew          151
Pokemon 6     Goodra          706
----------------------------------------
             Name  Pokedex No.
Pokemon 2  Meowth           52
----------------------------------------
Meowth

In [58]:
# Add a new column

data = {"Name" : ["Pikachu" , "Meowth" , "Charizard" , "Dragonite" , "Mew" , "Goodra"],
        "Pokedex No.": [25,52,6,149,151,706]}

df = pd.DataFrame(data , index = ['Pokemon 1','Pokemon 2','Pokemon 3','Pokemon 4','Pokemon 5','Pokemon 6'])

print(df)

print('---------------------------------------------------------')


df['Type'] = ['Electric','Normal','Fire/Flying','Dragon/Flying','Psychic','Dragon']

print(df)

print('---------------------------------------------------------')

# Add a new row : Easiest way to add row is to create a dataframe and concatenate.

new_row = pd.DataFrame([{"Name": "Sylveon" , "Pokedex No.":700 , "Type" : "Fairy" }] , index = ["Pokemon 7"])

df = pd.concat([df, new_row])

print(df)

                Name  Pokedex No.
Pokemon 1    Pikachu           25
Pokemon 2     Meowth           52
Pokemon 3  Charizard            6
Pokemon 4  Dragonite          149
Pokemon 5        Mew          151
Pokemon 6     Goodra          706
---------------------------------------------------------
                Name  Pokedex No.           Type
Pokemon 1    Pikachu           25       Electric
Pokemon 2     Meowth           52         Normal
Pokemon 3  Charizard            6    Fire/Flying
Pokemon 4  Dragonite          149  Dragon/Flying
Pokemon 5        Mew          151        Psychic
Pokemon 6     Goodra          706         Dragon
---------------------------------------------------------
                Name  Pokedex No.           Type
Pokemon 1    Pikachu           25       Electric
Pokemon 2     Meowth           52         Normal
Pokemon 3  Charizard            6    Fire/Flying
Pokemon 4  Dragonite          149  Dragon/Flying
Pokemon 5        Mew          151        Psychic
Pokemon 6     Goodra          706         Dragon
Pokemon 7    Sylveon          700          Fairy

In [59]:
# Add new rows
new_rows = pd.DataFrame([{"Name": "Darkrai" , "Pokedex No.":491 , "Type" : "Dark" },
                         {"Name": "Gengar" , "Pokedex No.":94 , "Type" : "Ghost/Poison"},
                         {"Name": "Pheromosa" , "Pokedex No.":795 , "Type" : "Bug/Fighting"}] , index = ["Pokemon 8" , "Pokemon 9" , "Pokemon 10"])

df = pd.concat([df, new_rows])

print(df)

                 Name  Pokedex No.           Type
Pokemon 1     Pikachu           25       Electric
Pokemon 2      Meowth           52         Normal
Pokemon 3   Charizard            6    Fire/Flying
Pokemon 4   Dragonite          149  Dragon/Flying
Pokemon 5         Mew          151        Psychic
Pokemon 6      Goodra          706         Dragon
Pokemon 7     Sylveon          700          Fairy
Pokemon 8     Darkrai          491           Dark
Pokemon 9      Gengar           94   Ghost/Poison
Pokemon 10  Pheromosa          795   Bug/Fighting

Imports : CSV and JSON

In [6]:
df = pd.read_csv(r"D:\Python training\datasets\pokemon.csv")

df.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [10]:
df = pd.read_json(r"D:\Python training\datasets\pokemon_data.json")

print(df.head())

# print(df.to_string())

                    name             type  total  hp  attack
0              Bulbasaur  [Grass, Poison]    318  45      49
1                Ivysaur  [Grass, Poison]    405  60      62
2               Venusaur  [Grass, Poison]    525  80      82
3  VenusaurMega Venusaur  [Grass, Poison]    625  80     100
4             Charmander           [Fire]    309  39      52

Selection Techniques in Python

In [18]:
df = pd.read_csv(r"D:\Python training\datasets\pokemon.csv")

# print(df.head())

print("-------------------------------------------------------------------------------------------------")

# Selection by column:

print(df['Name'].head())

print("-------------------------------------------------------------------------------------------------")

print(df['Type 1'].tail())

print("-------------------------------------------------------------------------------------------------")

print(df[["Name" , "Type 1" , "Type 2"]])

-------------------------------------------------------------------------------------------------
0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
Name: Name, dtype: str
-------------------------------------------------------------------------------------------------
795       Rock
796       Rock
797    Psychic
798    Psychic
799       Fire
Name: Type 1, dtype: str
-------------------------------------------------------------------------------------------------
                      Name   Type 1  Type 2
0                Bulbasaur    Grass  Poison
1                  Ivysaur    Grass  Poison
2                 Venusaur    Grass  Poison
3    VenusaurMega Venusaur    Grass  Poison
4               Charmander     Fire     NaN
..                     ...      ...     ...
795                Diancie     Rock   Fairy
796    DiancieMega Diancie     Rock   Fairy
797    HoopaHoopa Confined  Psychic   Ghost
798     HoopaHoopa Unbound  Psychic    Dark
799              Volcanion     Fire   Water

[800 rows x 3 columns]

In [ ]:
# Selection by Rows:

print(df.loc[0])

#                     1
Name          Bulbasaur
Type 1            Grass
Type 2           Poison
Total               318
HP                   45
Attack               49
Defense              49
Sp. Atk              65
Sp. Def              65
Speed                45
Generation            1
Legendary         False
Name: 0, dtype: object

OR, set an index column. So you can acess the row by any one the column value. For eg : If Name is setup as index column, we can access a row from any value in the Name column.

In [24]:
df = pd.read_csv(r"D:\Python training\datasets\pokemon.csv" , index_col = "Name")

print(df.loc["Pikachu"])

print("-------------------------------------------------------------------------------------------------")

print(df.loc["Goodra" , ['Type 1' , 'Type 2' , 'Generation']])

#                   25
Type 1        Electric
Type 2             NaN
Total              320
HP                  35
Attack              55
Defense             40
Sp. Atk             50
Sp. Def             50
Speed               90
Generation           1
Legendary        False
Name: Pikachu, dtype: object
-------------------------------------------------------------------------------------------------
Type 1        Dragon
Type 2           NaN
Generation         6
Name: Goodra, dtype: object

In [30]:
print(df.loc["Pidgey" : "Spearow" ])

                      #  Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  \
Name
Pidgey               16  Normal  Flying    251  40      45       40       35
Pidgeotto            17  Normal  Flying    349  63      60       55       50
Pidgeot              18  Normal  Flying    479  83      80       75       70
PidgeotMega Pidgeot  18  Normal  Flying    579  83      80       80      135
Rattata              19  Normal     NaN    253  30      56       35       25
Raticate             20  Normal     NaN    413  55      81       60       50
Spearow              21  Normal  Flying    262  40      60       30       31

                     Sp. Def  Speed  Generation  Legendary
Name
Pidgey                    35     56           1      False
Pidgeotto                 50     71           1      False
Pidgeot                   70    101           1      False
PidgeotMega Pidgeot       80    121           1      False
Rattata                   35     72           1      False
Raticate                  70     97           1      False
Spearow                   31     70           1      False

In [29]:
print(df.loc["Pidgey" : "Spearow" ,['Type 1' , 'Type 2' , 'Generation']])

                     Type 1  Type 2  Generation
Name
Pidgey               Normal  Flying           1
Pidgeotto            Normal  Flying           1
Pidgeot              Normal  Flying           1
PidgeotMega Pidgeot  Normal  Flying           1
Rattata              Normal     NaN           1
Raticate             Normal     NaN           1
Spearow              Normal  Flying           1

In [ ]:
print(df.iloc[0:11:2 , 0:3])   # df.iloc[start:end:step , column_start : column_end]

                           # Type 1  Type 2
Name
Bulbasaur                  1  Grass  Poison
Venusaur                   3  Grass  Poison
Charmander                 4   Fire     NaN
Charizard                  6   Fire  Flying
CharizardMega Charizard Y  6   Fire  Flying
Wartortle                  8  Water     NaN

In [39]:
df = pd.read_csv(r"D:\Python training\datasets\pokemon.csv" , index_col = "Name")

try:
    pokemon = input("Enter the pokemon whose description you would fancy : ").capitalize()

    print(df.loc[pokemon])

    print("----------------------------------------------------")

    stat = input("Any specific stat that you prefer: ").capitalize()

    print(df.loc[pokemon , stat])

except KeyError:
    print(f"{pokemon} doesnot exist in the pokedex")

#                704
Type 1        Dragon
Type 2           NaN
Total            300
HP                45
Attack            50
Defense           35
Sp. Atk           55
Sp. Def           75
Speed             40
Generation         6
Legendary      False
Name: Goomy, dtype: object
----------------------------------------------------
Dragon

Filtering : Keeping the rows that match the condition

In [53]:
df = pd.read_csv(r"D:\Python training\datasets\data_pkmn.csv")

tall_pokemon = df[df["Height"] >= 2]

# print(tall_pokemon)

heavy_pokemon = df[df["Weight"] >= 100]
 
heavy_pokemon


legendary = df[df["Legendary"] == 1] # OR  legendary = df[df["Legendary"] == True]  (Boolean value true also returns 1 so that works too)

legendary

water_pokemon = df[(df["Type1"] == "Water") | (df["Type2"] == "Water")]

water_pokemon

fire_flying_pokemon = df[(df["Type1"]== "Fire") & (df["Type2"] == "Flying")]

fire_flying_pokemon

      No       Name Type1   Type2  Height  Weight  Legendary
5      6  Charizard  Fire  Flying     1.7    90.5          0
145  146    Moltres  Fire  Flying     2.0    60.0          1

Aggregate functions: Functions that reduces set of values  into a single summary value. Used to summarize and analyze data.

Often used with groupby() function.

In [ ]:
# Aggregate Functions for Whole datasets.

df = pd.read_csv(r"D:\Python training\datasets\data_pkmn.csv")

# print(df.mean(numeric_only = True))   # Find the mean of any columns that are numeric

df.sum(numeric_only = True)

df.min(numeric_only = True)

df.max(numeric_only = True)

df.count()         # NaN is ignored by count. So they won't count

No           150
Name         150
Type1        150
Type2         67
Height       150
Weight       150
Legendary    150
dtype: int64

In [60]:
# Column Specific aggregate functions

print(df["Height"].mean())   

print(df["Weight"].sum())

print(df['Height'].min())

print(df['Weight'].max())

print(df["Type2"].count())

1.2
6934.700000000001
0.2
460.0
67

In [69]:
# Group by

group = df.groupby("Type1")

# print(group["Height"].mean())

group["Height"].sum()

group["Height"].min()

group["Weight"].max()

group['Name'].count()

Type1
Bug         12
Dragon       3
Electric     9
Fairy        2
Fighting     7
Fire        12
Ghost        3
Grass       12
Ground       8
Ice          2
Normal      22
Poison      14
Psychic      7
Rock         9
Water       28
Name: Name, dtype: int64

Data cleaning : The process of fixing/removing incomplete, incorrect or irrelevant data.

The main work pandas is used for is data cleaning.

In [70]:
df = pd.read_csv(r"D:\Python training\datasets\data_pkmn.csv")

Drop columns :

In [75]:
df_new = df.drop(columns = "Legendary")

print(df_new.head())

df_new = df.drop(columns = ['No' , 'Weight'])

df_new.head()

   No        Name  Type1   Type2  Height  Weight
0   1   Bulbasaur  Grass  Poison     0.7     6.9
1   2     Ivysaur  Grass  Poison     1.0    13.0
2   3    Venusaur  Grass  Poison     2.0   100.0
3   4  Charmander   Fire     NaN     0.6     8.5
4   5  Charmeleon   Fire     NaN     1.1    19.0

         Name  Type1   Type2  Height  Legendary
0   Bulbasaur  Grass  Poison     0.7          0
1     Ivysaur  Grass  Poison     1.0          0
2    Venusaur  Grass  Poison     2.0          0
3  Charmander   Fire     NaN     0.6          0
4  Charmeleon   Fire     NaN     1.1          0

Handle Missing and Inconsistent Data :

In [96]:
df = pd.read_csv(r"D:\Python training\datasets\data_pkmn.csv")

# Drop missing values
df_new= df.dropna(subset = ["Type2"])
df_new.head(10)

# Replace missing values
df_new2 = df.fillna({"Type2" : "None"})
df_new2.head(15)

# Fix inconsistent values

df["Type1"] = df["Type1"].replace({"Grass" : "GHAS", "Fire" : "AAGH", "Water" : "PANI"})
df.head(10)


# Standardize text

df["Name"] = df["Name"].str.lower()
df.head(10)

# Fix or chnage Data Types

df["Legendary"] = df["Legendary"].astype(bool)
df.tail(10)

# Remove duplicate Values
df.head()

df = df.drop_duplicates()

df.head()

   No        Name Type1   Type2  Height  Weight  Legendary
0   1   bulbasaur  GHAS  Poison     0.7     6.9      False
1   2     ivysaur  GHAS  Poison     1.0    13.0      False
2   3    venusaur  GHAS  Poison     2.0   100.0      False
3   4  charmander  AAGH     NaN     0.6     8.5      False
4   5  charmeleon  AAGH     NaN     1.1    19.0      False